### ISSUE TITLE
Could not find any source related to SpecFication.

### ISSUE THREAD

**Issue by JJaaang** [HexHive/specrop#1]
Hi! 
I read the SpecROP paper with great interest.
So, I wanted to search for gadgets using SpecFication!
But... I couldn't find the relevant code.
Would you mind if I ask you to confirm it?!

**Comment by andsanmar** [comment]
Hi, you're right. The codebase was being cleaned up and we never uploaded it, we will do it in the next couple of days.

**Comment by JJaaang** [comment]
Thank you for your quick reply.
I'll look forward to it.
I wish you have a nice day : )

**Comment by andsanmar** [comment]
Hello, I updated the repository with SpecFication code, let me know if it works for you by reopening the issue.

**Comment by JJaaang** [comment]
It seems to be working well! thank you :)
